trigger:
  branches:
    include:
      - main

parameters:
- name: diskSize
  displayName: Disk Size (GB)
  type: string
  default: '128'

stages:

#=================================================
# DEV DEPLOY
#=================================================

- stage: DEV
  displayName: Deploy DEV

  jobs:

  - template: templates/terraform.yml
    parameters:
      environment: dev
      action: apply
      diskSize: ${{ parameters.diskSize }}

#=================================================
# DESTROY DEV
#=================================================

- stage: DESTROY_DEV
  displayName: Destroy DEV

  dependsOn: DEV
  condition: succeeded()

  jobs:

  - template: templates/terraform.yml
    parameters:
      environment: dev
      action: destroy
      diskSize: ${{ parameters.diskSize }}

#=================================================
# QA DEPLOY
#=================================================

- stage: QA
  displayName: Deploy QA

  dependsOn: DESTROY_DEV
  condition: succeeded()

  jobs:

  - template: templates/terraform.yml
    parameters:
      environment: qa
      action: apply
      diskSize: ${{ parameters.diskSize }}

#=================================================
# PROD DEPLOY
#=================================================

- stage: PROD

  displayName: Deploy PROD

  dependsOn: QA

  condition: succeeded()

  jobs:

  - deployment: PROD

    displayName: Deploy PROD

    environment: PROD

    strategy:

      runOnce:

        deploy:

          steps:

          - template: templates/terraform-steps.yml

            parameters:
              environment: prod
              action: apply
              diskSize: ${{ parameters.diskSize }}