trigger:
  branches:
    include:
      - main

parameters:
- name: diskSize
  displayName: Disk Size (GB)
  type: string
  default: '128'

stages:

#--------------------------------------
# DEV
#--------------------------------------

- stage: DEV
  displayName: Deploy DEV

  jobs:
  - job: DeployDEV
    steps:
    - template: templates/terraform-steps.yml
      parameters:
        environment: dev
        diskSize: ${{ parameters.diskSize }}

#--------------------------------------
# DELETE DEV VM
#--------------------------------------

- stage: DELETE_DEV_VM
  displayName: Delete DEV VM

  dependsOn: DEV
  condition: succeeded()

  jobs:

  - job: DeleteVM
    displayName: Delete DEV VM

    steps:

    - task: AzureCLI@2
      displayName: Delete DEV VM
      inputs:
        azureSubscription: Azure-ServiceConnection
        scriptType: bash
        scriptLocation: inlineScript

        inlineScript: |

          az vm delete \
            --resource-group rg-dev-demo \
            --name vm-dev-linux \
            --yes

#--------------------------------------
# QA
#--------------------------------------

- stage: QA
  displayName: Deploy QA

  dependsOn: DELETE_DEV_VM
  condition: succeeded()

  jobs:
  - job: DeployQA
    steps:
    - template: templates/terraform-steps.yml
      parameters:
        environment: qa
        diskSize: ${{ parameters.diskSize }}

#--------------------------------------
# PROD
#--------------------------------------

- stage: PROD
  displayName: Deploy PROD

  dependsOn: QA
  condition: succeeded()

  jobs:

  - deployment: PROD
    displayName: Deploy PROD

    environment: PROD

    strategy:
      runOnce:
        deploy:

          steps:

          - template: templates/terraform-steps.yml
            parameters:
              environment: prod
              diskSize: ${{ parameters.diskSize }}