trigger:
  branches:
    include:
      - main

parameters:
- name: diskSize
  displayName: Disk Size (GB)
  type: string
  default: '128'

stages:

#=========================
# DEV
#=========================

- stage: DEV

  displayName: Deploy DEV

  jobs:

  - template: templates/terraform-deploy.yml

    parameters:
      environment: dev
      diskSize: ${{ parameters.diskSize }}

#=========================
# QA
#=========================

- stage: QA

  displayName: Deploy QA

  dependsOn: DEV

  condition: succeeded()

  jobs:

  - template: templates/terraform-deploy.yml

    parameters:
      environment: qa
      diskSize: ${{ parameters.diskSize }}

#=========================
# PROD
#=========================

- stage: PROD

  displayName: Deploy PROD

  dependsOn: QA

  condition: succeeded()

  jobs:

  - deployment: Deploy_PROD

    displayName: Deploy Production

    environment: PROD

    strategy:

      runOnce:

        deploy:

          steps:

          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.15.8'

          - task: AzureCLI@2
            inputs:
              azureSubscription: Azure-ServiceConnection
              scriptType: bash
              scriptLocation: inlineScript

              inlineScript: |

                terraform init \
                  -reconfigure \
                  -backend-config="key=prod.terraform.tfstate"

                terraform validate

                terraform plan \
                  -var-file="environments/prod.tfvars" \
                  -var="data_disk_size_gb=${{ parameters.diskSize }}" \
                  -out=tfplan

                terraform apply \
                  -auto-approve \
                  tfplan