name: Azure Infrastructure Deployment

on:

  workflow_dispatch:

    inputs:

      diskSize:

        description: Disk Size (GB)

        required: true

        default: "128"

permissions:
  id-token: write
  contents: read

jobs:

#-----------------------------------
# DEV
#-----------------------------------

  dev:

    uses: ./.github/workflows/terraform.yml

    with:
      environment: dev
      diskSize: ${{ github.event.inputs.diskSize }}

#-----------------------------------
# DELETE VM
#-----------------------------------

  delete-dev:

    needs: dev

    runs-on: ubuntu-latest

    environment: DEV

    steps:

    - uses: azure/login@v2

      with:

        client-id: ${{ secrets.AZURE_CLIENT_ID }}

        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - run: |

        az vm delete \
          --resource-group rg-dev-demo \
          --name vm-dev-linux \
          --yes

#-----------------------------------
# QA
#-----------------------------------

  qa:

    needs: delete-dev

    uses: ./.github/workflows/terraform.yml

    with:

      environment: qa

      diskSize: ${{ github.event.inputs.diskSize }}

#-----------------------------------
# PROD
#-----------------------------------

  prod:

    needs: qa

    uses: ./.github/workflows/terraform.yml

    with:

      environment: prod

      diskSize: ${{ github.event.inputs.diskSize }}